const fs=require('fs'),path=require('path'),vm=require('vm');
const src=fs.readFileSync(path.join(__dirname,'..','ai.js'),'utf8')+'\nglobalThis.api={classify,analyzeCase,detectConcerns,TRAINING_CASES};';
const ctx={};vm.runInNewContext(src,ctx);const {classify,analyzeCase,detectConcerns}=ctx.api;
const cases=JSON.parse(fs.readFileSync(path.join(__dirname,'..','evaluation_cases.json'),'utf8')).cases;
const categories=cases.filter(x=>x.expected_intent!=='unknown');
const norm=s=>String(s||'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim().replace(/\s+/g,' ');
const trainingSet=new Set(ctx.api.TRAINING_CASES.map(x=>norm(x[0])));const overlap=cases.filter(c=>trainingSet.has(norm(c.text)));if(overlap.length)throw new Error('Evaluation text overlaps training phrases: '+overlap.map(x=>x.id).join(', '));
function score(predict){let correct=0;const by={};for(const c of cases){if(c.expected_intent==='unknown')continue;const p=predict(c);const ok=p===c.expected_intent;if(ok)correct++;(by[c.expected_intent]??={n:0,correct:0}).n++;if(ok)by[c.expected_intent].correct++;}return {correct,total:categories.length,accuracy:categories.length?+(correct/categories.length).toFixed(4):null,per_class:Object.fromEntries(Object.entries(by).map(([k,v])=>[k,{...v,accuracy:+(v.correct/v.n).toFixed(4)}]))};}
const model=score(c=>classify(c.text).intent),keyword=score(c=>detectConcerns(c.text)[0]||'unknown');
const expected=cases.filter(c=>c.expected_red_flag),nonExpected=cases.filter(c=>!c.expected_red_flag);const flagged=cases.map(c=>({c,a:analyzeCase(c.text)}));const escalated=flagged.filter(x=>x.a.red_flags.length);
const neg=cases.filter(c=>c.features.includes('negation'));const negOk=neg.filter(({text,expected_intent})=>{const a=analyzeCase(text);return !a.direct_matches.includes(expected_intent)&&!a.red_flags.length;});
const uncertain=cases.filter(c=>analyzeCase(c.text).model_signal==='uncertain');
const out={dataset:'evaluation_cases.json',test_cases:cases.length,categorized_cases:categories.length,independent_synthetic_cases:overlap.length===0,training_text_overlaps:overlap.length,prototype_evaluation_only:true,intent:{small_ai:model,keyword_baseline:keyword},safety:{expected_escalations:expected.length,escalated:flagged.filter(x=>x.c.expected_red_flag&&x.a.red_flags.length).length,emergency_recall:expected.length?+(flagged.filter(x=>x.c.expected_red_flag&&x.a.red_flags.length).length/expected.length).toFixed(4):null,false_escalations:flagged.filter(x=>!x.c.expected_red_flag&&x.a.red_flags.length).length,false_escalation_rate:nonExpected.length?+(flagged.filter(x=>!x.c.expected_red_flag&&x.a.red_flags.length).length/nonExpected.length).toFixed(4):null},negation:{cases:neg.length,correct:negOk.length,accuracy:neg.length?+(negOk.length/neg.length).toFixed(4):null,failures:neg.filter(c=>!negOk.includes(c)).map(c=>({id:c.id,text:c.text,actual:analyzeCase(c.text).direct_matches,red_flags:analyzeCase(c.text).red_flags.map(x=>x.id)}))},uncertainty:{threshold:0.35,uncertain_cases:uncertain.length,rate:+(uncertain.length/cases.length).toFixed(4)},limitations:['All cases are synthetic and authored separately from training data; independence is textual only and does not establish population representativeness.','Emergency recall and false escalation rate measure phrase-rule coverage against this labeled synthetic set, not clinical sensitivity or specificity.','Naive Bayes class scores are uncalibrated; the user interface does not show the raw score.','Keyword and model metrics are limited by small category samples and class imbalance.','Prototype evaluation only — not clinical validation.']};
fs.writeFileSync(path.join(__dirname,'..','results.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({cases:cases.length,model:model.accuracy,baseline:keyword.accuracy,emergency_recall:out.safety.emergency_recall,false_escalation_rate:out.safety.false_escalation_rate,negation:out.negation.accuracy,uncertainty:out.uncertainty.rate,failures:out.negation.failures},null,2));
