const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const sandbox={};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','ai.js'),'utf8')+'\nglobalThis.api={analyzeCase};',sandbox);const {analyzeCase}=sandbox.api;
const tests=[
['positive breathing','shash nite koshto hocche','breathing_difficulty',true,true],['negated breathing','shash nite koshto hocche na','breathing_difficulty',false,false],['positive seizure','bacchar khichuni hocche','seizure',true,true],['negated seizure','khichuni hocche na','seizure',false,false],['Bangla script','শ্বাস নিতে কষ্ট হচ্ছে','breathing_difficulty',true,true],['Banglish','bacchar shash korte koshto','breathing_difficulty',true,true],['typo','shash e kosto hocche','breathing_difficulty',true,true],['mixed language','amar baby r breathing problem','breathing_difficulty',true,true],['financial barrier','hospital e jawar taka nai','financial_barrier',true,false],['transport barrier','hospital onek dure gari nai','travel_barrier',true,false],['empty input','',null,false,false],['ambiguous input','kichu ekta oshubidha','unknown',false,false],['urgent and financial','amar bacchar shash nite koshto hocche hospital e jawar taka nai','breathing_difficulty',true,true],['multiple symptoms','jor ar kashi hocche','fever',true,false],['negated breathing problem','shash nite ekdom problem nai','breathing_difficulty',false,false],['no chest pain','no chest pain today','chest_cardiac_warning',false,false],['fever negation','amar bacchar jor nai','fever',false,false],['chest pain negation','buk betha nei','chest_cardiac_warning',false,false],['vomiting negation','vomit korche na','diarrhea_vomiting',false,false],['unable breathing phrasing','baccha shash nite partese na','breathing_difficulty',true,true],
['unconsciousness','not responding or waking','',false,true],['severe confusion','suddenly very confused and drowsy','',false,true],['severe bleeding','অনেক রক্ত পড়ছে, বন্ধ হচ্ছে না','',false,true],['cannot drink','পানি খেতে পারছে না, প্রস্রাব কম','dehydration',true,true],['severe dehydration','চোখ বসে গেছে জিহ্বা শুকনো','dehydration',true,true],['chest warning','squeezing chest pain now','chest_cardiac_warning',true,true],['sudden weakness','suddenly one arm weak','neurological_red_flag',true,true],['face droop','face drooping suddenly','neurological_red_flag',true,true],['speech difficulty','speech suddenly slurred','neurological_red_flag',true,true],['serious head trauma','struck his head hard and vomiting','injury_trauma',true,true],['pregnancy warning','pregnancy bleeding heavily','maternal_pregnancy',true,true],['snakebite','snake bite on leg','',false,true],['poisoning','child drank poison','',false,true]
];
for(const [name,text,intent,signal,red] of tests){const a=analyzeCase(text);if(intent==='unknown')assert.equal(a.intent,'unknown',name);if(intent)assert.equal(a.direct_matches.includes(intent),signal,`${name} signal`);assert.equal(a.red_flags.length>0,red,`${name} red flag (${a.red_flags.map(x=>x.id)})`);}
console.log(`Passed ${tests.length} language, negation, classifier and safety tests.`);


